created: 2023-08-15T16:04:07.042Z
creator:
  id: b7f6076a-3da9-4836-b31f-4c3bdfa6ec33
  name: Jesse Shatsky
deletedAt: null
deployedAt: null
deployedCommitId: null
folderId: 4fefba06-24c0-4001-8a06-71e77f0542e4
id: cd195f79-b5c7-4be5-9dc9-8aba7f0b3678
isDeployed: false
isEditable: true
isPublic: false
name: Custom Components 8/15 Prod Testing
organizationId: 71b53980-0a9d-45dc-a4e8-5efd62ebfb1f
pages:
  - id: 09ee662b-14af-4b12-bd6f-8dfe62fbf96f
    isDefault: true
settings:
  profiles:
    deployed:
      availableProfileIds:
        - 431d2084-be9f-46c4-b44e-8632bb72084d
        - bedc7639-78d3-4b13-ad79-5fc86dfc94d5
      defaultProfileId: 431d2084-be9f-46c4-b44e-8632bb72084d
    editor:
      availableProfileIds:
        - 431d2084-be9f-46c4-b44e-8632bb72084d
        - bedc7639-78d3-4b13-ad79-5fc86dfc94d5
      defaultProfileId: bedc7639-78d3-4b13-ad79-5fc86dfc94d5
    preview:
      availableProfileIds:
        - 431d2084-be9f-46c4-b44e-8632bb72084d
        - bedc7639-78d3-4b13-ad79-5fc86dfc94d5
      defaultProfileId: bedc7639-78d3-4b13-ad79-5fc86dfc94d5
updated: 2023-08-15T16:04:07.042Z
userPermissions:
  - manage:applications
  - read:applications
  - publish:applications
  - makePublic:applications
