// WARNING: This file is automatically generated and managed by Superblocks CLI and should not be edited manually.
// Use the `superblocks components watch` command to regenerate this file from its source in config.ts

// All properties of your component are defined here.
// These are the properties which are surfaced in the Superblocks properties panel
// and can be referenced throughout your Superblocks Application
export interface Props {
  checked: boolean;
  labelPosition: string;
  label: string;
  description: string;
  size: string;
  radius: string;
  color: string;
  disabled: boolean;
}

export interface EventTriggers {
  // Call the subsequent function(s) to trigger event(s) in Superblocks from your component.
  // These events can be wired up to event handlers in your Superblocks App
  onChange: () => void;
}
